### ISSUE TITLE
task repeat

### ISSUE THREAD

**Issue by llrex56** [davidmarquis/redis-scheduler#3]
i have a problem in sping boot，the task repeat

**Comment by davidmarquis** [comment]
It will be very hard to get help without more details. Please provide more details on your issue.

**Comment by llrex56** [comment]
@Bean
    public RedisTaskScheduler redisTaskScheduler() {
        RedisTemplateDriver redisTemplateDriver = new RedisTemplateDriver(redisTemplate);
        RedisTaskScheduler scheduler = new RedisTaskScheduler(redisTemplateDriver, taskId -> {
            System.err.printf("task running... with param: [%s], time: [%s] \n",
                    taskId, DateFormatUtils.format(new Date(), "yyyy-MM-dd HH:mm:ss"));
        });
        // redis-scheduler.aomi
        scheduler.setSchedulerName("aomi");
        scheduler.setPollingDelayMillis(3000);
        scheduler.start();
        return scheduler;
    }
------
i load the redisTaskScheduler after application start, and then run with the method scheduleAt, it will  run twice but no every time

**Comment by llrex56** [comment]
`@Bean
    public RedisTaskScheduler redisTaskScheduler() {
        RedisTemplateDriver redisTemplateDriver = new RedisTemplateDriver(redisTemplate);
        RedisTaskScheduler scheduler = new RedisTaskScheduler(redisTemplateDriver, taskId -> {
            System.err.printf("task running... with param: [%s], time: [%s] \n",
                    taskId, DateFormatUtils.format(new Date(), "yyyy-MM-dd HH:mm:ss"));
        });
        // redis-scheduler.aomi
        scheduler.setSchedulerName("aomi");
        scheduler.setPollingDelayMillis(3000);
        scheduler.start();
        return scheduler;
    }`
----
i load the redisTaskScheduler after application start, and then run with the method scheduleAt, it will run twice but no every time

**Comment by llrex56** [comment]
```
    @Bean
    public RedisTaskScheduler redisTaskScheduler() {
        RedisTemplateDriver redisTemplateDriver = new RedisTemplateDriver(redisTemplate);
        RedisTaskScheduler scheduler = new RedisTaskScheduler(redisTemplateDriver, taskId -> {
            System.err.printf("task running... with param: [%s], time: [%s] \n",
                    taskId, DateFormatUtils.format(new Date(), "yyyy-MM-dd HH:mm:ss"));
        });
        // redis-scheduler.aomi
        scheduler.setSchedulerName("aomi");
        scheduler.setPollingDelayMillis(3000);
        scheduler.start();
        return scheduler;
    }
```
----
i load the redisTaskScheduler after application start, and then run with the method scheduleAt, it will run twice but no every time
